repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.0  # Use the latest stable version of ruff-pre-commit
    hooks:
      - id: ruff
        args: [--fix]  # Automatically fix issues (formatting and linting)
        language_version: python3.9  # Adjust this to match your Python version